name: 'Terraform'

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4
            
      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions/@master
        with:
          tf_actions_version: 0.13.4
          tf_actions_subcommand: 'plan'
        env:
          args: '-var="SUBSCRIPTION_ID=${{ secrets.AZ_SUBSCRIPTION_ID }}" -var="TENANT_ID=${{ secrets.AZ_TENANT_ID }}" -var="CLIENT_ID=${{ secrets.TF_CLIENT_ID }}" -var="CLIENT_SECRET=${{ secrets.TF_CLIENT_SECRET }}" '                
      - name: 'Terraform Apply'
        run: terraform apply
